### ISSUE TITLE
Script Error: attempt to call global 'Player_max_damage' (a nil value)

### ISSUE THREAD

**Issue by mryayayify** [CloudOfShame/BrutalOblige#8] opened 2017-08-14 14:58 UTC
Everytime i try to build up a map on Oblige 7.666 with the Brutal Addon, it fails when i use Brutal Doom and a bunch of adjustments made using OBLIGE. I've tried a bunch of things and it failed.

When i tried Single Level it also creates an error, "Script Error: wad_insert_file: cannot open file: brutaloblige/decorates/BrutalMonsters.dec"

**Comment by CloudOfShame** [comment] 2017-08-17 16:54
Is this against the release or the master branch?

    a bunch of adjustments

Could you be more specific?

    When i tried Single Level it also creates an error, "Script Error: wad_insert_file: cannot open file: brutaloblige/decorates/BrutalMonsters.dec"

Make sure you are compiling the pk3 correctly. This issue has come up before and [in that case](https://github.com/CloudOfShame/BrutalOblige/issues/6) it was a problem with how the pk3 had been zipped up.

**Comment by mryayayify** [comment] 2017-08-25 00:50
master branch

**Comment by alphatonic** [comment] 2017-10-29 20:51
Same problem here. 
My BrutalOblige.pk3 looks like this inside:
root directory: ![oblige_screenshot_brutaloblige](https://user-images.githubusercontent.com/16276413/32148157-ee591032-bcf2-11e7-8113-32631d2713bc.png)

**Comment by CloudOfShame** [comment] 2017-10-30 18:25
I think I've found this one, seems my edited version of items.lua has fallen out of sync with the vanilla version as of 7.666. Player_max_damage() is a function in the 7.666 item.lua script which isn't in mine (presumably it wasnt in 7.5).

**Comment by CloudOfShame** [comment] 2017-10-30 20:35
I found the cause of the pairs issue, which is what the edited item script was a workaround for in the first place. The mg42 had it's ammo type as 'clip' rather than 'bullets'. Commit 24b6717a4c7ebdadc53eff2fa1a27c2daf34936f fixes this and removes the edited item script.

The removal of the edited item.lua fixes this issue. Closing.

**Closed by CloudOfShame** 2017-10-30 20:35 UTC

**Comment by alphatonic** [comment] 2017-10-31 10:39
Awesome thank you very much.

**Comment by CloudOfShame** [comment] 2017-10-31 17:53
My first impression from the log is that it's not loading brutalv20b.pk3, although when I try and repeat that my log looks different. Could you try loading it manually (i.e. gzdoom -file brutalv20b.pk3 oblige.wad) and let me know if you get the same result?

**Comment by alphatonic** [comment] 2017-10-31 20:40
Sure, here: https://pastebin.com/VhFS2dEp

**Comment by CloudOfShame** [comment] 2017-11-01 17:17
Yeah I see the problem, I haven't updated for Brutality 3.0 yet. I didn't realise 3.0 was out yet tbh. I'll get on that.

**Comment by alphatonic** [comment] 2017-11-01 19:42
Cool thank you. :)
